language: c++
dist: trusty
sudo: required

env:
  matrix:
    - TRAVIS_NO_EMPTY_JOB=true

matrix:
  exclude:
    - env: TRAVIS_NO_EMPTY_JOB=true

  include:
    - env: COMPILER=clang++-5.0 JOBS=1 TEST_TYPE=configure-gl TEST_LEVEL=minimal GL_LIBS=all-apis

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"
  - sudo apt-get -qq update
  - sudo apt-get -y install cmake-3.9 

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - git submodule init && git submodule update
  - ./init
  - ./build
  - ./test

notifications:
email: false
