language: c++
dist: trusty
sudo: false

env:
  matrix:
    - TRAVIS_NO_EMPTY_JOB=true

matrix:
  exclude:
    - env: TRAVIS_NO_EMPTY_JOB=true

  include:
    - env: COMPILER=clang++-6.0 JOBS=1 TEST_TYPE=configure-gl TEST_LEVEL=minimal GL_LIBS=all-apis
      addons: &clang6
        apt:
          packages:
            - clang-6.0
            - cmake-3.9
            - mesa-common-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - george-edison55/cmake-3.x

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main"
  - sudo apt-get -qq update

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - git submodule init && git submodule update
  - ./init
  - ./build
  - ./test

notifications:
email: false
