#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

./init

tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'pixel'`

cp build-make/bin/* $tmpdir
cp -r pixel/assets $tmpdir

(cd $tmpdir && zip -r pixel.zip * )
mv $tmpdir/pixel.zip .
rm -rf $tmpdir
