<?xml version="1.0" encoding="UTF-8"?>
<tileset name="mario" tilewidth="16" tileheight="16" tilecount="924" columns="33">
 <image source="mario.png" width="528" height="448"/>
 <tile id="0" type="brick"/>
 <tile id="1" type="brick"/>
 <tile id="2" type="brick"/>
 <tile id="3" type="brick"/>
 <tile id="4" type="pipe"/>
 <tile id="5" type="brick"/>
 <tile id="33" type="brick"/>
 <tile id="34" type="brick"/>
 <tile id="35" type="brick"/>
 <tile id="37" type="pipe"/>
 <tile id="66" type="brick"/>
 <tile id="67" type="brick"/>
 <tile id="68" type="brick"/>
 <tile id="70" type="pipe"/>
 <tile id="99" type="brick"/>
 <tile id="100" type="brick"/>
 <tile id="101" type="brick"/>
 <tile id="103" type="pipe"/>
 <tile id="132" type="brick"/>
 <tile id="133" type="brick"/>
 <tile id="134" type="brick"/>
 <tile id="136" type="pipe"/>
 <tile id="165" type="brick"/>
 <tile id="166" type="brick"/>
 <tile id="167" type="brick"/>
 <tile id="169" type="pipe"/>
 <tile id="198" type="brick"/>
 <tile id="199" type="brick"/>
 <tile id="200" type="brick"/>
 <tile id="202" type="pipe"/>
 <tile id="231" type="brick"/>
 <tile id="232" type="brick"/>
 <tile id="233" type="brick"/>
 <tile id="235" type="pipe"/>
 <tile id="264" type="pipe"/>
 <tile id="265" type="pipe"/>
 <tile id="266" type="pipe"/>
 <tile id="267" type="pipe"/>
 <tile id="268" type="pipe"/>
 <tile id="269" type="platform"/>
 <tile id="270" type="platform"/>
 <tile id="271" type="platform"/>
 <tile id="297" type="pipe"/>
 <tile id="298" type="pipe"/>
 <tile id="299" type="pipe"/>
 <tile id="300" type="pipe"/>
 <tile id="301" type="pipe"/>
 <tile id="302" type="platform"/>
 <tile id="303" type="platform"/>
 <tile id="304" type="platform"/>
 <tile id="330" type="pipe"/>
 <tile id="331" type="pipe"/>
 <tile id="332" type="pipe"/>
 <tile id="333" type="pipe"/>
 <tile id="334" type="pipe"/>
 <tile id="335" type="platform"/>
 <tile id="336" type="platform"/>
 <tile id="337" type="platform"/>
 <tile id="363" type="pipe"/>
 <tile id="364" type="pipe"/>
 <tile id="365" type="pipe"/>
 <tile id="366" type="pipe"/>
 <tile id="367" type="pipe"/>
 <tile id="368" type="platform"/>
 <tile id="369" type="platform"/>
 <tile id="370" type="platform"/>
 <tile id="396" type="pipe"/>
 <tile id="397" type="pipe"/>
 <tile id="398" type="pipe"/>
 <tile id="399" type="pipe"/>
 <tile id="400" type="pipe"/>
 <tile id="401" type="platform"/>
 <tile id="402" type="platform"/>
 <tile id="403" type="platform"/>
 <tile id="429" type="pipe"/>
 <tile id="430" type="pipe"/>
 <tile id="431" type="pipe"/>
 <tile id="432" type="pipe"/>
 <tile id="433" type="pipe"/>
 <tile id="434" type="platform"/>
 <tile id="435" type="platform"/>
 <tile id="436" type="platform"/>
 <tile id="462" type="pipe"/>
 <tile id="463" type="pipe"/>
 <tile id="464" type="pipe"/>
 <tile id="465" type="pipe"/>
 <tile id="466" type="pipe"/>
 <tile id="467" type="platform"/>
 <tile id="468" type="platform"/>
 <tile id="469" type="platform"/>
 <tile id="495" type="pipe"/>
 <tile id="496" type="pipe"/>
 <tile id="497" type="pipe"/>
 <tile id="498" type="pipe"/>
 <tile id="499" type="pipe"/>
 <tile id="500" type="platform"/>
 <tile id="501" type="platform"/>
 <tile id="502" type="platform"/>
 <tile id="528" type="pipe"/>
 <tile id="529" type="pipe"/>
 <tile id="530" type="pipe"/>
 <tile id="531" type="pipe"/>
 <tile id="532" type="pipe"/>
 <tile id="533" type="platform"/>
 <tile id="534" type="platform"/>
 <tile id="535" type="platform"/>
 <tile id="561" type="pipe"/>
 <tile id="562" type="pipe"/>
 <tile id="563" type="pipe"/>
 <tile id="564" type="pipe"/>
 <tile id="565" type="pipe"/>
 <tile id="566" type="platform"/>
 <tile id="567" type="platform"/>
 <tile id="568" type="platform"/>
 <tile id="594" type="pipe"/>
 <tile id="595" type="pipe"/>
 <tile id="596" type="pipe"/>
 <tile id="597" type="pipe"/>
 <tile id="598" type="pipe"/>
 <tile id="599" type="platform"/>
 <tile id="600" type="platform"/>
 <tile id="601" type="platform"/>
 <tile id="627" type="pipe"/>
 <tile id="628" type="pipe"/>
 <tile id="629" type="pipe"/>
 <tile id="630" type="pipe"/>
 <tile id="631" type="pipe"/>
 <tile id="632" type="platform"/>
 <tile id="633" type="platform"/>
 <tile id="634" type="platform"/>
 <tile id="660" type="cloud"/>
 <tile id="661" type="cloud"/>
 <tile id="662" type="cloud"/>
 <tile id="665" type="cloud"/>
 <tile id="666" type="cloud"/>
 <tile id="667" type="cloud"/>
 <tile id="693" type="cloud"/>
 <tile id="694" type="cloud"/>
 <tile id="695" type="cloud"/>
 <tile id="698" type="cloud"/>
 <tile id="699" type="cloud"/>
 <tile id="700" type="cloud"/>
 <tile id="726" type="cloud"/>
 <tile id="727" type="cloud"/>
 <tile id="728" type="cloud"/>
 <tile id="731" type="cloud"/>
 <tile id="732" type="cloud"/>
 <tile id="733" type="cloud"/>
 <tile id="759" type="cloud"/>
 <tile id="760" type="cloud"/>
 <tile id="761" type="cloud"/>
 <tile id="764" type="cloud"/>
 <tile id="765" type="cloud"/>
 <tile id="766" type="cloud"/>
 <tile id="792" type="cloud"/>
 <tile id="793" type="cloud"/>
 <tile id="794" type="cloud"/>
 <tile id="797" type="cloud"/>
 <tile id="798" type="cloud"/>
 <tile id="799" type="cloud"/>
 <tile id="825" type="cloud"/>
 <tile id="826" type="cloud"/>
 <tile id="827" type="cloud"/>
 <tile id="830" type="cloud"/>
 <tile id="831" type="cloud"/>
 <tile id="832" type="cloud"/>
 <tile id="858" type="cloud"/>
 <tile id="859" type="cloud"/>
 <tile id="860" type="cloud"/>
 <tile id="863" type="cloud"/>
 <tile id="864" type="cloud"/>
 <tile id="865" type="cloud"/>
 <tile id="891" type="cloud"/>
 <tile id="892" type="cloud"/>
 <tile id="893" type="cloud"/>
 <tile id="894" type="sky">
  <properties>
   <property name="werthers" value="original"/>
  </properties>
 </tile>
 <tile id="896" type="cloud"/>
 <tile id="897" type="cloud"/>
 <tile id="898" type="cloud"/>
</tileset>
